### ISSUE TITLE
How can i install this? 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [ssh0/dotfiles#2]
After cloning how might I install this?

**Comment by ssh0** [comment]
@AbhimanyuAryan If you want to use some configuration file, you can use it by copying it (or make symbolic-link) to the right place (ex. `xmonad/xmonad.hs` to `~/.xmonad/xmonad.hs`).

And also you might need other files if you like [my video](https://www.youtube.com/watch?v=qjG3wfyKY58).
- `xmonad/xmobarrc`
- `bin/cplay.sh`
- `bin/sound_volume_change_wrapper.sh`
- and some `bin/*` files written in `xmonad.hs`
- install xmonad, ranger, luakit, tmux, vim, zsh

**Another answer**

If you want to apply almost all configurations (not recommended, be careful),  you can use dotfile management framework (listed in the section "General-purpose dotfile utilities" at https://dotfiles.github.io/).

I also write [dot](https://github.com/ssh0/dot) for managing this dotfiles repository.

Anyway, I will add some documentaion to README, thank you.

**Comment by AbhimanyuAryan** [comment]
@ssh0 you need to explain what all symbolic links i need to create. I want all of your stuff. 

Nick created a .dotfile for his osx configurations: https://github.com/nicknisi/dotfiles

and in video: https://www.youtube.com/watch?v=5r6yzFEXajQ  he explained his configuration and usage. 

He has written a `./install.sh` script which automatically downloads and installs stuff. Also creates symlinks. 

You have an extra ordinary config. which people might wanna use. But, there is no ease with using it :(

I have no idea about dot manager....so pretty much I have read everything about it to use your configuration. 

Anyways I wanna steal all of it not just the selective things.  I have newly installed Ubuntu 14.04.

**Comment by ssh0** [comment]
@AbhimanyuAryan OK, I understand.

**How to install all the stuff**

1:  install dot (manually or with zsh-plugin-manager). See [here](https://github.com/ssh0/dot#install).
2: change the dot's configuration file. See [here](https://github.com/ssh0/dot#configuration).

In this case (you will copy all the configurations from folked my repository),
run below in your terminal (of cource states after '#' is comment)

```
export DOT_REPO="https://github.com/AbhimanyuAryan/dotfiles-3.git" # your folked repository, right?
export DOT_DIR="$HOME/.dotfiles-3" # the directory of the above repository
```

3: run `dot set -v`.

then, this script makes all the symbolic links to your computer.
When you already have some files, it asks you whether to do each time (so don't worry about it).

If you want to get some other applications information (but not listed in dotfiles), you can see my [blog post](http://ssh0.hatenablog.com/entry/2015/08/31/%E3%80%90%E5%82%99%E5%BF%98%E9%8C%B2%E3%80%91Ubuntu%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%97%E3%81%9F%E3%81%82%E3%81%A8%E3%81%AB%E3%82%84%E3%81%A3%E3%81%9F%E3%81%93%E3%81%A8) (written in Japanese, sorry).

---

**Finally**, in my opinion, you shouldn't copy all the configurations from others.
Because you don't know what you do and some (good) default settings is ignored by that.
But you can steal some parts of configurations from others and modify it.

ref: [at 1h2m51s of "vim + tmux - OMG!Code" - YouTube](https://youtu.be/5r6yzFEXajQ?t=1h2m51s)

So I remove `setup.sh` or `dot` this repository and split it to other repository for `dot` command which manage _your_ dotfiles.

96f559e144b987b081401bf21224058e013616d7

If you want to know some specific configuration parts, feel free to contact to me.

**Comment by AbhimanyuAryan** [comment]
Thanks.
